version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - '**/*'
    groups:
      non-breaking-changes-security-updates:
        update-types: [minor, patch]
        applies-to: security-updates
        dependency-type: production
        patterns: ["*"]
      non-breaking-changes-version-updates:
        update-types: [minor, patch]
        applies-to: version-updates
        dependency-type: production
        patterns: ["*"]
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Etc/UTC"
